### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by olifog** [olifog/tf2stats#1]
Eventual end project will be comprised of multiple microprocesses, all intercommunicating with the Redis and MongoDB databases and the NextJS frontend.

- [x] set up initial monorepo
- [x] access control for mongoDB/redis, redis should be fine since hosted on same server as the script accessing it
- [ ] analyser script. Most important microprocess, serves as an Express API interfacing the redis leaderboards/weapon usages in a useful way, while also calling the Steam API and analysing requested steam IDs. Needs to update leaderboards, profiles, player data
- [ ] Lua script (included in the analyser script) hosted on the redis database, for collating all a user's ranks in leaderboards
- [ ] crawler script, finding new players for analysis and sending them to the analyser
- [ ] usage-calculator script, calculating usages for each class/weapon combo number/slot option combination and refreshing the redis store of them
- [ ] NextJS frontend
